FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN python -m venv /opt/venv && . /opt/venv/bin/activate \
 && pip install -r requirements.txt
ENV PATH="/opt/venv/bin:$PATH"
COPY . .
EXPOSE 8001
